version: "3.8"

services:
  # client:
  #   build: ./client
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - web
  #   environment:
  #     - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
  #   volumes:
  #     - ./client:/client
  #     - /client/node_modules

  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
